image: dcr.danawa.io/alpine-k8s

stages:
  - build
  - deploy

before_script:
  - export IMAGE="${REGISTRY}/${CI_PROJECT_TITLE}"

build:
  stage: build
  script:
    - export VERSION="$(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed -E 's/(version)|[:,\",]//g' | tr -d '[[:space:]]')"
    - echo "$IMAGE:latest"
    - echo "$IMAGE:$VERSION"
    - docker build -t ${IMAGE}:latest .
    - docker tag ${IMAGE}:latest ${IMAGE}:${VERSION}
    - docker push ${IMAGE}:latest
    - docker push ${IMAGE}:${VERSION}

deploy:
  stage: deploy
  script:
    - kubectl patch deployment -n hybrid-process hybrid-process-management -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}},\"spec\":{\"containers\":[{\"name\":\"hybrid-process-management\",\"image\":\"${IMAGE}:latest\"}]}}}}"
    - sleep 5
    - kubectl get pod -n hybrid-process -o wide

